---
apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: xstoragecontainers.azure.platform.upbound.io
spec:
  group: azure.platform.upbound.io
  names:
    categories:
      - crossplane
    kind: XStorageContainer
    plural: xstoragecontainers
  versions:
    - name: v1
      referenceable: true
      schema:
        openAPIV3Schema:
          description: XStorageContainer is the Schema for the XStorageContainer API.
          properties:
            spec:
              description: XStorageContainerSpec defines the desired state of XStorageContainer.
              properties:
                parameters:
                  properties:
                    deletionPolicy:
                      description: Delete the external resources when the Claim/XR is deleted. Defaults to Delete
                      enum:
                        - Delete
                        - Orphan
                      type: string
                      default: Delete
                    providerConfigName:
                      description: Crossplane ProviderConfig to use for provisioning this resources
                      type: string
                      default: default
                    region:
                      default: eastus
                      description: Azure Region
                      type: string
                    resourceGroup:
                      description: Existing Azure ResourceGroup. If empty, a ResourceGroup will be created.
                      type: string
                  type: object
              type: object
            status:
              description: XStorageContainerStatus defines the observed state of XStorageContainer.
              type: object
          required:
            - spec
          type: object
      served: true
