apiVersion: azure.platform.upbound.io/v1
kind: StorageContainer
metadata:
  name: ref-azure-storagecontainer-existing-rg
  namespace: default
spec:
  parameters:
    providerConfigName: default
    region: eastus
    resourceGroup: existing-rg
