apiVersion: azure.platform.upbound.io/v1
kind: StorageContainer
metadata:
  name: ref-azure-storagecontainer
  namespace: default
spec:
  parameters:
    providerConfigName: default
    region: eastus
